Fix: Correct AttributeError in CalibrationDialog
This commit fixes an `AttributeError: 'CalibrationDialog' object has no attribute 'publish_event'` that occurred when interacting with the model calibration and diagnostics dialog.

The `CalibrationDialog` was attempting to call `self.publish_event`, but this method was not defined on the class. The correct way to publish events from this dialog is to use the `ui_event_bus` on the `controller` instance, which is passed to the dialog's constructor.

This commit replaces all instances of `self.publish_event` with `self.controller.ui_event_bus.publish` in the `CalibrationDialog` class. It also proactively fixes a similar issue in the `ManageWeightsDialog` class.